# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9bbba107e90927696dac2a9344a3bec2"
name = "babalu-backend-draftorder"
handle = "babalu-backend-draftorder-1"
application_url = "https://effect-spy-bee-harris.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_draft_orders,write_draft_orders,read_products"

[auth]
redirect_urls = [
  "https://effect-spy-bee-harris.trycloudflare.com/auth/callback",
  "https://effect-spy-bee-harris.trycloudflare.com/auth/shopify/callback",
  "https://effect-spy-bee-harris.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
